merchex/merchex/urls.py
from django.contrib import admin
from django.urls import path

from listings import views

urlpatterns = [
    path("admin/", admin.site.urls),

    path("bands/", views.band_list, name='band-list'),
    path("bands/<int:id>/", views.band_detail, name='band-detail'),
    path("bands/add/", views.band_create, name='band-create'),

    path("listings/", views.listings),

    path("about-us/", views.about),
    path("contact-us/", views.contact, name='contact'),
]

merchex/listings/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models

class Band(models.Model):

    def __str__(self):
        return f'{self.name}'

    class Genre(models.TextChoices):
        HIP_HOP = 'HH'
        SYNTH_POP = 'SP'
        ALTERNATIVE_ROCK = 'AR'

    name = models.fields.CharField(max_length=100)
    genre = models.fields.CharField(choices=Genre.choices, max_length=5)
    biography = models.fields.CharField(max_length=1000)
    year_formed = models.fields.IntegerField(
       validators=[MinValueValidator(1900),
                   MaxValueValidator(2021)]
    )
    active = models.fields.BooleanField(default=True)
    official_homepage = models.fields.URLField(null=True, blank=True)
    # like_news = models.fields.BooleanField(default=False)

class Listing(models.Model):

    class ListingType(models.TextChoices):
        RECORD = 'R'
        CLOTHING = 'C'
        POSTER = 'P'
        MISC = 'M'

    title = models.fields.CharField(max_length=100)
    description = models.fields.CharField(max_length=100)
    sold = models.fields.BooleanField(default=False)
    year = models.fields.IntegerField(
        validators=[MinValueValidator(1900),
                    MaxValueValidator(2021)]
    )

    type = models.fields.CharField(choices=ListingType.choices, max_length=5)
    band = models.ForeignKey(Band, null=True, on_delete=models.SET_NULL)

merchex/listings/forms.py
from django import forms
from listings.models import Band, Listing

class ContactUsForm(forms.Form):
    name = forms.CharField(required=False)
    email = forms.EmailField()
    message = forms.CharField(max_length=1000)

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = '__all__'

merchex/listings/views.py
from django.shortcuts import render
from django.http import HttpResponse
from  django.shortcuts import redirect
from django.core.mail import send_mail

from listings.models import Band
from listings.forms import BandForm, ContactUsForm




def band_list(request):
    bands = Band.objects.all()
    return render(request,
                  'listings/band_list.html',
                  {'bands': bands})

def band_detail(request, id):
    band = Band.objects.get(id=id)
    return render(request,
                  'listings/band_detail.html',
                  {'band': band})

def band_create(request):
    if request.method == 'POST':
        form = BandForm(request.POST)
        if form.is_valid():
            band = form.save()
            return redirect('band-detail', band.id)

    else:
        form = BandForm()

    return render(request,
                  'listings/band_create.html',
                  {'form': form})


def about(request):
    return HttpResponse('<h1>À propos</h1> <p>Nous adorons merch !</p>')

def listings(request):
    return HttpResponse('<h1>Listings</h1> <p>Faites votre choix</p>')

def contact(request):

    if request.method =='POST':
        form = ContactUsForm(request.POST)

        if form.is_valid():
            send_mail(
                subject=f'Message from {form.cleaned_data["name"] or "anonyme" } via MerchEx Contact Us Form',
                message=form.cleaned_data['message'],
                from_email=form.cleaned_data['email'],
                recipient_list=['admin@merchex.xyz'],
            )
            return  redirect('email-sent')
    else:
        form = ContactUsForm()

    return render(request,
                  'listings/contact.html',
                  { 'form':form })

    print('La méthode de requête est : ', request.method)
    print('Les données POST sont :', request.POST)

    form = ContactUsForm()

merchex/listings/templates/listings/band_create.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Créer un nouveau groupe</h1>

<form action="" method="post" >
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer" />
</form>

{% endblock %}

merchex/listings/templates/listings/band_detail.html
{% extends 'listings/base.html' %}

{% block content %}

<h2>L'identifiant est {{ id }}</h2>

<ul>
    <li>Genre : {{ band.get_genre_display }}</li>
    <li>Année de formation : {{ band.year_formed }}</li>
    <li>Actif : {{ band.active|yesno }}</li>
    {% if band.official_homepage %}
    <li><a href="{{ band.official_homepage}}"> {{ band.official_homepage}} </a></li>
    {% endif %}
</ul>

<p>{{ band.biography }}</p>

<a href="{% url 'band-list'%}">Retour à tous les groupes</a>

{% endblock %}

merchex/listings/templates/listings/band_list.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Groupes</h1>

<a href="{% url 'band-create' %}">Créer un nouveau groupe</a>

<ul>
    {% for band in bands %}
    <li><a href="{% url 'band-detail' band.id %}">{{ band.name }}</a></li>
    {% endfor%}
</ul>

{% endblock %}

merchex/listings/templates/listings/base.html
{% load static %}
<html>
    <head>
      <title>Merchex</title>
      <link rel="stylesheet" href="{% static 'listings/style.css' %}" />
    </head>
    <body>
        <nav>
            <a href="{% url 'band-list' %}">Groupes</a>
            <a href="{% url 'contact'%}">Contact</a>
        </nav>
        {% block content %}{% endblock %}

    </body>
</html>

merchex/listings/templates/listings/contact.html
{% extends 'listings/base.html' %}

{% block content %}

<h1>Contactez-nous</h1>

<p>Nous sommes là pour vous aider.</p>

<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Envoyer">

</form>

{% endblock %}